language: android

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

android:
 components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

jdk: oraclejdk8

script: ./gradlew testDebug
